trigger:
- main

resources:
- repo: self

variables:

  # Existing Docker Registry service connection
  dockerRegistryServiceConnection: '5f17aea6-2582-4678-a83e-adc8c8288f2f'

  # ACR repository
  imageRepository: 'node'

  # ACR
  containerRegistry: 'staticacr.azurecr.io'

  # Dockerfile
  dockerfilePath: '$(Build.SourcesDirectory)/service1/Dockerfile'

  # Unique image version
  tag: '$(Build.BuildId)'

  # Azure DevOps agent
  vmImageName: 'ubuntu-latest'

  # NEW Azure Resource Manager service connection
  azureSubscription: 'test'

  # Container App
  containerAppName: 'vcheck'

  # Resource Group
  resourceGroup: 'Arjit'


stages:

# ========================================
# BUILD + PUSH IMAGE
# ========================================

- stage: Build
  displayName: Build and Push

  jobs:
  - job: Build

    pool:
      vmImage: $(vmImageName)

    steps:

    - task: Docker@2
      displayName: Build and Push Image to ACR

      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)

        # IMPORTANT
        buildContext: '$(Build.SourcesDirectory)'

        tags: |
          $(tag)


# ========================================
# DEPLOY TO CONTAINER APP
# ========================================

- stage: Deploy
  displayName: Deploy to Container App

  dependsOn: Build

  condition: succeeded()

  jobs:
  - job: Deploy

    pool:
      vmImage: $(vmImageName)

    steps:

    - task: AzureContainerApps@1
      displayName: Deploy Image to vcheck

      inputs:
        azureSubscription: $(azureSubscription)
        containerAppName: $(containerAppName)
        resourceGroup: $(resourceGroup)
        imageToDeploy: '$(containerRegistry)/$(imageRepository):$(tag)'
