steps:
  # Upload index.html to the GCS bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'index.html', 'gs://cicdbucketnew']

  # List bucket contents for verification
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['ls', 'gs://cicdbucketnew']

  # Invalidate CDN cache for the load balancer
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud compute url-maps invalidate-cdn-cache cicdlbfrontend --path "/*" --async
