steps:
  # Upload only the updated index.html to the bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'index.html', 'gs://$_BUCKET_NAME/index.html']

  # Verify the updated index.html in the bucket (for debugging)
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['ls', 'gs://$_BUCKET_NAME/index.html']

  # Invalidate the cache for index.html
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'compute'
      - 'url-maps'
      - 'invalidate-cache'
      - '$_URL_MAP_NAME'
      - '--path'
      - '/index.html'
      - '--async'

substitutions:
  _BUCKET_NAME: 'cicdbucketnew'
  _URL_MAP_NAME: 'cicdlbfrontend'

options:
  logging: CLOUD_LOGGING_ONLY
