steps:
  # Sync all files to the bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['rsync', '-r', '.', 'gs://$_BUCKET_NAME']

  # Verify the files in the bucket (for debugging)
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['ls', 'gs://$_BUCKET_NAME']

  # Invalidate the cache
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'compute'
      - 'url-maps'
      - 'invalidate-cache'
      - '$_URL_MAP_NAME'
      - '--path'
      - '/*'
      - '--async'

substitutions:
  _BUCKET_NAME: 'cicdbucketnew'
  _URL_MAP_NAME: 'cicdlbfrontend'

options:
  logging: CLOUD_LOGGING_ONLY
