steps:
  # Sync only the index.html file to the bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'index.html', 'gs://$_BUCKET_NAME']

  # Verify that index.html is updated in the bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['ls', 'gs://$_BUCKET_NAME']

  # Invalidate the CDN cache
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute url-maps invalidate-cdn-cache $_URL_MAP_NAME --path "/" --async || echo "Cache invalidation failed."

substitutions:
  _BUCKET_NAME: 'cicdbucketnew'
  _URL_MAP_NAME: 'cicdlbfrontend'

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: 'ALLOW_LOOSE'
